/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use std::path::Path;

use ui_tests::*;

macro_rules! generate_variant {
    ($fn_name:ident, $name:expr, $file:tt, $lang:expr, $style:expr, $cpp_compat:expr) => {
        #[test]
        fn $fn_name() {
            run_generate_test($name, Path::new($file), $lang, $style, $cpp_compat);
        }
    };
}

macro_rules! compile_variant {
    ($fn_name:ident, $expectation:expr, $lang:expr, $style:expr, $skip_warn:expr, $cpp_compat:expr) => {
        #[test]
        fn $fn_name() {
            run_compile_check(
                Path::new($expectation),
                $lang,
                $style,
                $skip_warn,
                $cpp_compat,
            );
        }
    };
}

// This file is generated by build.rs
include!(concat!(env!("OUT_DIR"), "/tests.rs"));

#[test]
fn test_manifest_up_to_date() {
    check_manifest_up_to_date(KNOWN_CBINDGEN_CASES, KNOWN_CHEADERGEN_CASES);
}
