use std::path::Path;

use cbindgen_ui_tests::*;

macro_rules! generate_variant {
    (header_diff, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            generate_variant!(@header_diff_body $($rest)*);
        }
    };
    (generation_fails, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            generate_variant!(@generation_fails_body $($rest)*);
        }
    };
    (skip, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        #[ignore]
        fn $fn_name() {
            generate_variant!(@body $($rest)*);
        }
    };
    ($fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            generate_variant!(@body $($rest)*);
        }
    };
    (@body $name:expr, $variant_path:expr, $file:tt, $lang:expr, $style:expr, $cpp_compat:expr) => {
        run_generate_test($name, Path::new($file), $lang, $style, $cpp_compat)
    };
    (@header_diff_body $name:expr, $variant_path:expr, $file:tt, $lang:expr, $style:expr, $cpp_compat:expr) => {
        run_header_diff_test($name, $variant_path, Path::new($file), $lang, $style, $cpp_compat)
    };
    (@generation_fails_body $name:expr, $variant_path:expr, $file:tt, $lang:expr, $style:expr, $cpp_compat:expr) => {
        run_generation_fails_test($name, $variant_path, Path::new($file), $lang, $style, $cpp_compat)
    };
}

macro_rules! compile_variant {
    (compilation_fails, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            compile_variant!(@compilation_fails_body $($rest)*);
        }
    };
    (header_diff, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            compile_variant!(@body $($rest)*);
        }
    };
    (generation_fails, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            compile_variant!(@body $($rest)*);
        }
    };
    (skip, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        #[ignore]
        fn $fn_name() {
            compile_variant!(@body $($rest)*);
        }
    };
    ($fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            compile_variant!(@body $($rest)*);
        }
    };
    (@body $name:expr, $variant_path:expr, $expectation:expr, $lang:expr, $style:expr, $skip_warn:expr, $cpp_compat:expr) => {
        run_compile_check(
            Path::new($expectation),
            $lang,
            $style,
            $skip_warn,
            $cpp_compat,
        )
    };
    (@compilation_fails_body $name:expr, $variant_path:expr, $expectation:expr, $lang:expr, $style:expr, $skip_warn:expr, $cpp_compat:expr) => {
        run_compilation_fails_check(
            Path::new($expectation),
            $lang,
            $style,
            $skip_warn,
            $cpp_compat,
        )
    };
}

macro_rules! symbol_test {
    (header_diff, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            symbol_test!(@header_diff_body $($rest)*);
        }
    };
    (generation_fails, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            symbol_test!(@generation_fails_body $($rest)*);
        }
    };
    (skip, $fn_name:ident, $($rest:tt)*) => {
        #[test]
        #[ignore]
        fn $fn_name() {
            symbol_test!(@body $($rest)*);
        }
    };
    ($fn_name:ident, $($rest:tt)*) => {
        #[test]
        fn $fn_name() {
            symbol_test!(@body $($rest)*);
        }
    };
    (@body $name:expr, $file:tt) => {
        run_symbol_test($name, Path::new($file))
    };
    (@header_diff_body $name:expr, $file:tt) => {
        run_header_diff_symbol_test($name, Path::new($file))
    };
    (@generation_fails_body $name:expr, $file:tt) => {
        run_generation_fails_symbol_test($name, Path::new($file))
    };
}

// This file is generated by build.rs
include!(concat!(env!("OUT_DIR"), "/tests.rs"));

#[test]
fn test_manifest_up_to_date() {
    check_manifest_up_to_date(KNOWN_CBINDGEN_CASES);
}
