experimental = ["setup-scripts"]

[store]
dir = "target/nextest"

[scripts.setup.compute-cbindgen-metadata]
command = ["ui-tests/cbindgen/tests/setup-metadata.sh"]

[scripts.setup.compute-cheadergen-metadata]
command = ["ui-tests/cheadergen/tests/setup-metadata.sh"]

[scripts.setup.build-cheadergen]
command = ["cheadergen_cli/tests/setup.sh"]

[[profile.default.scripts]]
filter = 'package(=cbindgen-ui-tests) & (test(~::generate::) | test(~::symbol::))'
setup = 'compute-cbindgen-metadata'

[[profile.default.scripts]]
filter = 'package(=cheadergen-ui-tests) & (test(~::generate::) | test(~::symbol::))'
setup = 'compute-cheadergen-metadata'

[[profile.default.scripts]]
filter = 'binary(~cli_errors)'
setup = 'build-cheadergen'

[profile.machine.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true
