experimental = ["setup-scripts"]

[store]
dir = "target/nextest"

[scripts.setup.compute-metadata]
command = ["tests/setup-metadata.sh"]

[[profile.default.scripts]]
filter = 'test(~::generate::)'
setup = 'compute-metadata'
