[package]
name = "cheadergen_cli"
version.workspace = true
edition.workspace = true
description = "A tool for generating C bindings to Rust code."
license.workspace = true
repository.workspace = true
keywords = ["bindings", "ffi", "code-generation"]
categories = ["external-ffi-bindings", "development-tools::ffi"]
include = ["rust-docs-toolchain", "src"]

[[bin]]
name = "cheadergen"
path = "src/main.rs"

[dependencies]
annotate-snippets = "0.11"
anyhow = "1"
bincode = "2"
camino = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
fs-err = "3"
heck = "0.5"
pathdiff = "0.2"
petgraph = "0.8"
guppy = { workspace = true }
rustdoc_ir = { workspace = true }
rustdoc_processor = { workspace = true }
rustdoc_resolver = { workspace = true }
rustdoc-types = { workspace = true }
xdg-home = "1"

[dev-dependencies]
tempfile = "3"
insta = "1"
