[book]
title = "cheadergen"
description = "Generate C/C++ headers from Rust libraries that expose a `pub extern \"C\"` API."
authors = ["Luca Palmieri"]
language = "en"
src = "src"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/LukeMathWalker/cheadergen"
edit-url-template = "https://github.com/LukeMathWalker/cheadergen/edit/main/docs/{path}"
site-url = "/"
default-theme = "rust"
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true
level = 1
