[package]
name = "cheadergen"
version.workspace = true
edition.workspace = true
description = "Annotations for controlling C/C++ header generation from Rust."
license.workspace = true
repository.workspace = true

[dependencies]
cheadergen_macros = { workspace = true }

[dev-dependencies]
trybuild = "1"
