name: verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: extractions/setup-just@v2
      - run: just lint

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v6
      - run: uv tool install cython
      - run: just coverage codecov
      - uses: codecov/codecov-action@v5
        with:
          files: codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  xfail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@nextest
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v6
      - run: uv tool install cython
      - run: just test-cbindgen-xfail

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
